---
title: "Summarise CPUE data"
author: "Max Lindmark"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  df_print: paged
  code_folding: hide
pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align ='center'
)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Load libraries

```{r, message=FALSE}
library(tidyverse)
```

## Read data

```{r, message=FALSE}
d <- read.csv("data/clean/catch_by_length.csv")

# Summarize total density by haul and size-class
d_sad <- d %>% 
  mutate(size_cl = ifelse(length_cm > 15 & length_cm < 50, "cod_sad", "all")) |> 
  group_by(haul_id, size_cl) %>% 
  summarise(density = sum(density)) %>% 
  ungroup() |> 
  filter(!size_cl == "all")

d_pel <- d %>% 
  mutate(size_cl = ifelse(length_cm > 20, "cod_pel", "all")) |> 
  group_by(haul_id, size_cl) %>% 
  summarise(density = sum(density)) %>% 
  ungroup() |> 
  filter(!size_cl == "all")

d_sum <- bind_rows(d_sad, d_pel) |> pivot_wider(names_from = size_cl, values_from = density)

ggplot(d_sum, aes(cod_pel, cod_sad)) + geom_point()

# Now left join in all other information...
d_haul <- d %>% 
  distinct(haul_id, .keep_all = TRUE) %>% 
  dplyr::select(-density, -length_cm)

d_haul <- left_join(d_haul, d_sum, by = "haul_id")

# Check distributions of densities across hauls
d_haul %>% 
  pivot_longer(c(cod_sad, cod_pel)) %>% 
  ggplot(aes(log(value))) + 
  geom_histogram() + 
  facet_wrap(~name, scales = "free_y")

# Save!
write_csv(d_haul, "data/clean/catch_clean.csv")
```
